- name: Force Ansible to use Python 3.9
  ansible.builtin.set_fact:
    ansible_python_interpreter: /usr/bin/python3.9

- name: Install Mysql Server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start MySQL Service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes

- name: Install PyMySQL Mysql client
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3.9

- name: Check the DB connection with our password
  community.mysql.mysql_info:
    login_user: root
    login_password: ExpenseApp@1
    #login_password: "{{ mysql_password }}"
    login_host: mysql-dev.awsdevops.sbs
    filter: version
  register: mysql_connection_output
  #ignore_errors: yes

- name: set up mysql password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
  #ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ mysql_password }}
  when: mysql_connection_output.failed is true

